version: '3.9'

services:
  db:
    container_name: postgres-db
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


  api:
    container_name: loyalty_api
    build:
      context: ./app_components/api
      dockerfile: Dockerfile
    ports:
      - 8008:8000
    volumes:
      - ./app_components/api:/api
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy


ds:
    container_name: ds_service
    build:
      context: ./app_components/ds
      dockerfile: Dockerfile
    volumes:
      - ./app_components/ds:/ds
    ports:
      - "3000:3000"
    depends_on:
      - db